---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: coder-sharing-io@ii.coop
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          rfc2136:
            tsigKeyName: pair
            tsigAlgorithm: HMACMD5
            tsigSecretSecretRef:
              name: tsig-powerdns
              key: powerdns
            nameserver: ${LB_IP}
        selector:
          dnsNames:
            - "*.coder.sharing.io"
            - "coder.sharing.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: coder
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.coder.sharing.io"
  dnsNames:
    - "*.coder.sharing.io"
    - "coder.sharing.io"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: cert-manager-tls
